### ISSUE TITLE
Maybe bug?

### ISSUE THREAD

**Issue by ghost** [llamasoft/Puca-Power#28] opened 2016-08-04 19:45 UTC
Not happening for every card, but it for some cards in Have list, PP1.4.4 believes I've twice the number of cards, triggering false trade alerts. 

Let me know if I can help troubleshoot, what additional info you need, etc?

And as always, thanks for this beauteous script. :)

**Comment by llamasoft** [comment] 2016-08-07 20:24
It looks like this actually a PucaTrade issue, not a Puca Power one.  (Possible duplicate of #24.)
PucaTrade only checks that you have a card that a user wants, not that you have enough to supply all of their wants.

**Closed as completed by llamasoft** 2016-08-07 20:24 UTC
